/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    inquiries: Inquiry;
    leads: Lead;
    'agent-threads': AgentThread;
    'agent-routines': AgentRoutine;
    'agent-memory': AgentMemory;
    pages: Page;
    projects: Project;
    articles: Article;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'agent-threads': AgentThreadsSelect<false> | AgentThreadsSelect<true>;
    'agent-routines': AgentRoutinesSelect<false> | AgentRoutinesSelect<true>;
    'agent-memory': AgentMemorySelect<false> | AgentMemorySelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    about: About;
    'services-page': ServicesPage;
    'work-page': WorkPage;
    'journal-page': JournalPage;
    'contact-page': ContactPage;
    navigation: Navigation;
    site: Site;
    effects: Effect;
    'not-found': NotFound;
    privacy: Privacy;
    terms: Term;
    agent: Agent;
    outreach: Outreach;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'work-page': WorkPageSelect<false> | WorkPageSelect<true>;
    'journal-page': JournalPageSelect<false> | JournalPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
    effects: EffectsSelect<false> | EffectsSelect<true>;
    'not-found': NotFoundSelect<false> | NotFoundSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    agent: AgentSelect<false> | AgentSelect<true>;
    outreach: OutreachSelect<false> | OutreachSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Messages from the contact form. Change the status as you work through them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  budget?: string | null;
  message: string;
  status: 'new' | 'in-progress' | 'replied' | 'archived' | 'spam';
  /**
   * Only visible here.
   */
  notes?: string | null;
  source?: {
    page?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Businesses that could use a better website. Keeper finds and checks them; you send the messages (from the phone app, or here).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  /**
   * e.g. hair salon
   */
  kind?: string | null;
  area?: string | null;
  country?: ('NG' | 'GH' | 'KE' | 'ZA' | 'GB' | 'IE' | 'US' | 'CA') | null;
  /**
   * International form, e.g. +2348031234567
   */
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  /**
   * Instagram, Facebook… (space-separated)
   */
  socials?: string | null;
  status: 'new' | 'checked' | 'ready' | 'contacted' | 'replied' | 'won' | 'lost' | 'skipped' | 'stopped';
  /**
   * 0–100: how much a new site would help and how easy they are to reach.
   */
  score?: number | null;
  /**
   * From the website check: what's wrong, in plain words.
   */
  summary?: string | null;
  /**
   * Keeper's notes from a phone-sized screenshot of their site.
   */
  review?: string | null;
  /**
   * Written by Keeper from what it found. Edit anything before sending.
   */
  messages?: {
    whatsapp?: string | null;
    sms?: string | null;
    emailSubject?: string | null;
    emailBody?: string | null;
    followUp?: boolean | null;
    writtenAt?: string | null;
  };
  /**
   * A free sample homepage made for them, at jomiez.com/preview/…
   */
  preview?: {
    slug?: string | null;
    content?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    madeAt?: string | null;
    /**
     * Times someone (not a link-preview robot) opened it.
     */
    views?: number | null;
    lastViewedAt?: string | null;
  };
  log?:
    | {
        at?: string | null;
        what?: string | null;
        id?: string | null;
      }[]
    | null;
  contactedAt?: string | null;
  followUps?: number | null;
  notes?: string | null;
  source?: ('openstreetmap' | 'manual' | 'keeper') | null;
  sourceId?: string | null;
  domain?: string | null;
  check?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  shot?: string | null;
  stopToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every task the agent has worked on: what it was asked, each step it took, and every change it made.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-threads".
 */
export interface AgentThread {
  id: number;
  title: string;
  owner?: (number | null) | User;
  source?: ('console' | 'page' | 'voice' | 'routine' | 'inbox') | null;
  status?: ('idle' | 'running' | 'waiting' | 'stopped' | 'error') | null;
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  messages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  provider?: string | null;
  events?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  plan?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pending?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  model?: string | null;
  usage?: {
    input?: number | null;
    output?: number | null;
  };
  routine?: (number | null) | AgentRoutine;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everyone who can sign in to this admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage the team and site settings; editors manage content.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Work the agent does on its own, on a schedule, with the permissions of the person who set it up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-routines".
 */
export interface AgentRoutine {
  id: number;
  name: string;
  /**
   * Write it as you would to a colleague. It can read, change and report on anything it's allowed to.
   */
  instruction: string;
  enabled?: boolean | null;
  schedule: 'hourly' | 'daily' | 'weekdays' | 'weekly' | 'monthly';
  /**
   * 24-hour time
   */
  time?: string | null;
  weekday?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  timezone?: string | null;
  mode?: ('inherit' | 'ask' | 'drafts' | 'trusted' | 'full') | null;
  owner?: (number | null) | User;
  nextRunAt?: string | null;
  lastRunAt?: string | null;
  lastStatus?: string | null;
  lastThread?: (number | null) | AgentThread;
  updatedAt: string;
  createdAt: string;
}
/**
 * What the agent knows and keeps in mind in every task: facts about the company, your preferences, and lessons from changes you turned down. Edit or delete anything.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-memory".
 */
export interface AgentMemory {
  id: number;
  content: string;
  kind?: ('fact' | 'preference' | 'voice' | 'lesson' | 'contact') | null;
  source?: ('you' | 'agent' | 'correction') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * New pages built from the site's sections. Each one lives at jomiez.com/<address>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            lead?: string | null;
            showCta?: boolean | null;
            cta?: {
              label: string;
              /**
               * Choose a page, or type any address (/about, /#pricing, https://…).
               */
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            title?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            image: number | Media;
            lead?: string | null;
            pill?: string | null;
            title: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBand';
          }
        | {
            title: string;
            items?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            label: string;
            projects: (number | Project)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            title: string;
            count: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'journal';
          }
        | {
            useSiteFaq?: boolean | null;
            custom?: {
              label?: string | null;
              sub?: string | null;
              title?: string | null;
              items?:
                | {
                    q: string;
                    a: string;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title: string;
            text?: string | null;
            cta: {
              label: string;
              /**
               * Choose a page, or type any address (/about, /#pricing, https://…).
               */
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'tenets';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
      )[]
    | null;
  /**
   * Link to this page from every page of the site.
   */
  placement?: {
    menu?: boolean | null;
    footer?: boolean | null;
    column?: string | null;
    /**
     * Leave empty to use the page title.
     */
    label?: string | null;
  };
  /**
   * The last part of the link: /<address>. Made from the title if left empty.
   */
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * All images used on the site. Replace a file here and it changes everywhere it's used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and search engines. Leave empty for decoration.
   */
  alt?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Our own products and the work we've built for clients. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * e.g. AI Platform, E-commerce
   */
  category: string;
  /**
   * Products get the full product page and appear under "Our products".
   */
  isProduct?: boolean | null;
  summary: string;
  /**
   * Shown on cards and at the top of the case study.
   */
  image?: (number | null) | Media;
  client?: string | null;
  year?: string | null;
  /**
   * Optional link to the live product.
   */
  link?: {
    label?: string | null;
    href?: string | null;
  };
  services?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        body?: string | null;
        points?:
          | {
              title: string;
              body: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  productPage?: {
    hero: {
      title?: string | null;
      lead?: string | null;
      cta: {
        label: string;
        /**
         * Choose a page, or type any address (/about, /#pricing, https://…).
         */
        href: string;
      };
      image?: (number | null) | Media;
      proof?: string | null;
    };
    stats?:
      | {
          value: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    showcase?: {
      title?: string | null;
      lead?: string | null;
      background?: (number | null) | Media;
      screen?: (number | null) | Media;
      address?: string | null;
    };
    cards?:
      | {
          title: string;
          text: string;
          mock?: ('research' | 'prompt') | null;
          mockTitle?: string | null;
          art?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    statement?: string | null;
    system?: {
      label?: string | null;
      text?: string | null;
      features?:
        | {
            icon:
              | 'arrowRightLight'
              | 'arrowRight'
              | 'trendUpLight'
              | 'rocketLight'
              | 'quotesFill'
              | 'timer'
              | 'xBold'
              | 'check'
              | 'phone'
              | 'whatsapp'
              | 'linkedin'
              | 'github'
              | 'instagram'
              | 'shieldCheck'
              | 'brain'
              | 'gauge'
              | 'plugsConnected'
              | 'magnifyingGlass'
              | 'paperPlaneTilt'
              | 'microphone'
              | 'slidersHorizontal'
              | 'lockSimple'
              | 'arrowClockwise'
              | 'caretLeft'
              | 'caretRight'
              | 'sidebarSimple'
              | 'downloadSimple'
              | 'export'
              | 'plus'
              | 'copy'
              | 'shield'
              | 'name';
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    faq?: {
      sub?: string | null;
      title?: string | null;
      items?:
        | {
            q: string;
            a: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * The last part of the link: /work/<address>. Made from the name if left empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Field notes shown on the home page and at /insights. Newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * One or two lines for cards and search results.
   */
  excerpt: string;
  image: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The last part of the link: /insights/<address>. Made from the title if left empty.
   */
  slug?: string | null;
  category: string;
  author: string;
  date: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Send old links to new pages (for example after renaming a project).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'agent-threads';
        value: number | AgentThread;
      } | null)
    | ({
        relationTo: 'agent-routines';
        value: number | AgentRoutine;
      } | null)
    | ({
        relationTo: 'agent-memory';
        value: number | AgentMemory;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  budget?: T;
  message?: T;
  status?: T;
  notes?: T;
  source?:
    | T
    | {
        page?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  area?: T;
  country?: T;
  phone?: T;
  email?: T;
  website?: T;
  address?: T;
  socials?: T;
  status?: T;
  score?: T;
  summary?: T;
  review?: T;
  messages?:
    | T
    | {
        whatsapp?: T;
        sms?: T;
        emailSubject?: T;
        emailBody?: T;
        followUp?: T;
        writtenAt?: T;
      };
  preview?:
    | T
    | {
        slug?: T;
        content?: T;
        madeAt?: T;
        views?: T;
        lastViewedAt?: T;
      };
  log?:
    | T
    | {
        at?: T;
        what?: T;
        id?: T;
      };
  contactedAt?: T;
  followUps?: T;
  notes?: T;
  source?: T;
  sourceId?: T;
  domain?: T;
  check?: T;
  shot?: T;
  stopToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-threads_select".
 */
export interface AgentThreadsSelect<T extends boolean = true> {
  title?: T;
  owner?: T;
  source?: T;
  status?: T;
  context?: T;
  messages?: T;
  provider?: T;
  events?: T;
  plan?: T;
  pending?: T;
  changes?: T;
  model?: T;
  usage?:
    | T
    | {
        input?: T;
        output?: T;
      };
  routine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-routines_select".
 */
export interface AgentRoutinesSelect<T extends boolean = true> {
  name?: T;
  instruction?: T;
  enabled?: T;
  schedule?: T;
  time?: T;
  weekday?: T;
  timezone?: T;
  mode?: T;
  owner?: T;
  nextRunAt?: T;
  lastRunAt?: T;
  lastStatus?: T;
  lastThread?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-memory_select".
 */
export interface AgentMemorySelect<T extends boolean = true> {
  content?: T;
  kind?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        pageHero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              showCta?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageBand?:
          | T
          | {
              image?: T;
              lead?: T;
              pill?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              label?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        journal?:
          | T
          | {
              title?: T;
              count?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              useSiteFaq?: T;
              custom?:
                | T
                | {
                    label?: T;
                    sub?: T;
                    title?: T;
                    items?:
                      | T
                      | {
                          q?: T;
                          a?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tenets?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  placement?:
    | T
    | {
        menu?: T;
        footer?: T;
        column?: T;
        label?: T;
      };
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  category?: T;
  isProduct?: T;
  summary?: T;
  image?: T;
  client?: T;
  year?: T;
  link?:
    | T
    | {
        label?: T;
        href?: T;
      };
  services?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        points?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        id?: T;
      };
  productPage?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              lead?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              image?: T;
              proof?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              text?: T;
              id?: T;
            };
        showcase?:
          | T
          | {
              title?: T;
              lead?: T;
              background?: T;
              screen?: T;
              address?: T;
            };
        cards?:
          | T
          | {
              title?: T;
              text?: T;
              mock?: T;
              mockTitle?: T;
              art?: T;
              id?: T;
            };
        statement?: T;
        system?:
          | T
          | {
              label?: T;
              text?: T;
              features?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    id?: T;
                  };
            };
        faq?:
          | T
          | {
              sub?: T;
              title?: T;
              items?:
                | T
                | {
                    q?: T;
                    a?: T;
                    id?: T;
                  };
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  image?: T;
  body?: T;
  slug?: T;
  category?: T;
  author?: T;
  date?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every section of the home page, in order. The switch at the top of each tab shows or hides it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    enabled?: boolean | null;
    titleMuted: string;
    titleMain: string;
    lead: string;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    /**
     * The wide photo behind the hero.
     */
    background?: (number | null) | Media;
    card?: {
      enabled?: boolean | null;
      title?: string | null;
      subtitle?: string | null;
      href?: string | null;
      image?: (number | null) | Media;
      /**
       * The coloured frame around the screenshot.
       */
      frame?: (number | null) | Media;
    };
    note?: string | null;
    showStack?: boolean | null;
  };
  intro: {
    enabled?: boolean | null;
    /**
     * Fills in word by word as visitors scroll.
     */
    statement: string;
    sub?: string | null;
    projects?: {
      value?: string | null;
      text?: string | null;
    };
    /**
     * The avatars are set in Site settings.
     */
    satisfaction?: {
      value?: string | null;
      label?: string | null;
    };
    years?: {
      value?: string | null;
      text?: string | null;
    };
    speed?: {
      title?: string | null;
      text?: string | null;
    };
    quote?: {
      text?: string | null;
      brand?: string | null;
      by?: string | null;
    };
    showTicker?: boolean | null;
  };
  work: {
    enabled?: boolean | null;
    /**
     * The huge word that scrolls across the section (e.g. "Creations").
     */
    marquee: string;
    /**
     * Leave empty to show the first six from Products & work.
     */
    projects?: (number | Project)[] | null;
  };
  services: {
    enabled?: boolean | null;
    label: string;
    intro?: string | null;
    title: string;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    texture?: (number | null) | Media;
    iso?: (number | null) | Media;
  };
  mission: {
    enabled?: boolean | null;
    label: string;
    /**
     * Fills in word by word as visitors scroll.
     */
    statement: string;
    body?: string | null;
    modelsIntro?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  tenets: {
    enabled?: boolean | null;
    /**
     * The huge word that scrolls across the section (e.g. "Our Tenets").
     */
    marquee: string;
    description?: string | null;
    /**
     * e.g. "A Jomiez tenet"
     */
    cardFooter?: string | null;
    items?:
      | {
          title: string;
          tag: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    showTicker?: boolean | null;
  };
  showcase: {
    enabled?: boolean | null;
    image?: (number | null) | Media;
    lead?: string | null;
    /**
     * e.g. "7+ years of craft"
     */
    pill?: string | null;
    title: string;
  };
  process: {
    enabled?: boolean | null;
    label: string;
    title: string;
    texture?: (number | null) | Media;
    iso?: (number | null) | Media;
    steps?:
      | {
          title: string;
          tag: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    closing?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
  };
  studio: {
    enabled?: boolean | null;
    statement: string;
    intro?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    /**
     * e.g. "Explore →"
     */
    exploreLabel?: string | null;
    disciplines?:
      | {
          name: string;
          role: string;
          body: string;
          image?: (number | null) | Media;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  pricing: {
    enabled?: boolean | null;
    /**
     * The huge word that scrolls across the section (e.g. "Pricing").
     */
    marquee: string;
    intro?: string | null;
    billing?: {
      left?: string | null;
      right?: string | null;
      hint?: string | null;
      leftNote?: string | null;
      rightNote?: string | null;
    };
    cardImage?: (number | null) | Media;
    tiers?:
      | {
          name: string;
          price: string;
          dark?: boolean | null;
          blurb: string;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          cta: {
            label: string;
            /**
             * Choose a page, or type any address (/about, /#pricing, https://…).
             */
            href: string;
          };
          id?: string | null;
        }[]
      | null;
    showTicker?: boolean | null;
  };
  faq: {
    enabled?: boolean | null;
    label: string;
    sub?: string | null;
    title: string;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    items?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
  };
  journal: {
    enabled?: boolean | null;
    /**
     * The huge word that scrolls across the section (e.g. "Journal").
     */
    marquee: string;
    intro?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    count: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The company page at /about.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero: {
    title: string;
    lead?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
  };
  mosaic?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  story: {
    enabled?: boolean | null;
    label: string;
    title: string;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    showStats?: boolean | null;
  };
  crafts: {
    enabled?: boolean | null;
    label: string;
    statement: string;
    lead?: string | null;
    showStack?: boolean | null;
    cards?:
      | {
          title: string;
          body: string;
          shape?: ('blocks' | 'zline' | 'rings' | 'diamond') | null;
          id?: string | null;
        }[]
      | null;
  };
  showTenets?: boolean | null;
  showFaq?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The services page at /services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    lead?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
  };
  showAccordion?: boolean | null;
  showProcess?: boolean | null;
  list: {
    enabled?: boolean | null;
    title: string;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  showFaq?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The page at /work that lists every product and project.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page".
 */
export interface WorkPage {
  id: number;
  image?: (number | null) | Media;
  /**
   * The huge word that scrolls across the section (e.g. "Creations").
   */
  marquee: string;
  /**
   * {products} and {builds} are replaced by the live counts.
   */
  note?: string | null;
  productsLabel?: string | null;
  clientsLabel?: string | null;
  /**
   * Words used on every case study page.
   */
  caseStudy: {
    productKicker?: string | null;
    caseKicker?: string | null;
    nextProduct?: string | null;
    nextCase?: string | null;
    ctaTitle?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
  };
  showFaq?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The journal index at /insights and the words around each post.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page".
 */
export interface JournalPage {
  id: number;
  /**
   * The huge word that scrolls across the section (e.g. "Journal").
   */
  marquee: string;
  intro?: string | null;
  post: {
    authorLabel?: string | null;
    dateLabel?: string | null;
    byLabel?: string | null;
    moreTitle?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The contact page at /contact, including the form's wording.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  split: {
    title: string;
    lead?: string | null;
    image?: (number | null) | Media;
    visualTitle?: string | null;
    form?: {
      nameLabel?: string | null;
      namePlaceholder?: string | null;
      emailLabel?: string | null;
      emailPlaceholder?: string | null;
      budgetLabel?: string | null;
      budgets?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      messageLabel?: string | null;
      messagePlaceholder?: string | null;
      submitLabel?: string | null;
      successMessage?: string | null;
      errorMessage?: string | null;
    };
  };
  call: {
    enabled?: boolean | null;
    image?: (number | null) | Media;
    label: string;
    title: string;
    body?: string | null;
    showSocials?: boolean | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
  };
  showFaq?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The links in the top bar and the footer, shown on every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header: {
    /**
     * Custom pages can add themselves here too: open the page and tick "Show in the top menu".
     */
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    showHire?: boolean | null;
    hire: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
  };
  footer: {
    /**
     * The scene behind the footer.
     */
    background?: (number | null) | Media;
    /**
     * {legalName} is replaced by the full company name.
     */
    blurb?: string | null;
    cta: {
      label: string;
      /**
       * Choose a page, or type any address (/about, /#pricing, https://…).
       */
      href: string;
    };
    followLabel?: string | null;
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * {year} and {legalName} are filled in automatically.
     */
    copyright?: string | null;
    showWordmark?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Company details, contact info, socials, search defaults and where contact messages go.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  legalName: string;
  /**
   * The live address, used for search engines and sharing (https://jomiez.com).
   */
  url: string;
  founder?: {
    name?: string | null;
    alias?: string | null;
    role?: string | null;
    /**
     * Shown in the Philosophy section. Leave empty to show the monogram.
     */
    photo?: (number | null) | Media;
    /**
     * The letter shown when there is no portrait.
     */
    monogram?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The small round faces on the home page and product pages.
   */
  avatars?: (number | Media)[] | null;
  /**
   * Shown in the scrolling strips. Known names get their logo.
   */
  stack?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  email: string;
  location?: string | null;
  phone?: string | null;
  /**
   * e.g. tel:+14252637569
   */
  phoneHref?: string | null;
  socials?:
    | {
        label: string;
        icon: 'whatsapp' | 'linkedin' | 'github' | 'instagram';
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The thin scrolling strip between sections.
   */
  ticker?: {
    enabled?: boolean | null;
    /**
     * e.g. "//JOMIEZ"
     */
    tag?: string | null;
    message?: string | null;
  };
  title: string;
  /**
   * %s is replaced by the page's own title.
   */
  titleTemplate: string;
  description: string;
  /**
   * 1200 × 630.
   */
  ogImage?: (number | null) | Media;
  notifications?: {
    /**
     * Leave empty to use the company email. Needs email set up (see ADMIN.md).
     */
    to?: string | null;
    autoReply?: boolean | null;
    autoReplySubject?: string | null;
    /**
     * {name} is replaced by the visitor's name.
     */
    autoReplyBody?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the liquid glass and motion effects on or off across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "effects".
 */
export interface Effect {
  id: number;
  cursorLens?: boolean | null;
  lensSize?: number | null;
  navGlass?: boolean | null;
  footerGlass?: boolean | null;
  heroDew?: boolean | null;
  pageTransitions?: boolean | null;
  smoothScroll?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What visitors see when a link is broken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found".
 */
export interface NotFound {
  id: number;
  title: string;
  body?: string | null;
  cta: {
    label: string;
    /**
     * Choose a page, or type any address (/about, /#pricing, https://…).
     */
    href: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The page at /privacy-policy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  title: string;
  intro: string;
  sections?:
    | {
        title: string;
        body?: string | null;
        intro?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Adds a last section with the company email and phone.
   */
  contactNote?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The page at /terms-conditions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  title: string;
  intro: string;
  sections?:
    | {
        title: string;
        body?: string | null;
        intro?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Adds a last section with the company email and phone.
   */
  contactNote?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The model that powers the agent, what it may do on its own, its voice and its limits.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent".
 */
export interface Agent {
  id: number;
  /**
   * Off stops every conversation, routine and automatic action at once.
   */
  enabled?: boolean | null;
  name: string;
  /**
   * The one it uses now. Its key comes from Your providers below.
   */
  provider:
    | 'anthropic'
    | 'openai'
    | 'google'
    | 'openrouter'
    | 'groq'
    | 'deepseek'
    | 'xai'
    | 'mistral'
    | 'together'
    | 'ollama'
    | 'custom';
  /**
   * The model's ID, exactly as the provider writes it (e.g. deepseek-v4-flash). Choose from your account to see every model your key can use, new ones included.
   */
  model: string;
  /**
   * How hard it thinks before acting, on models that support it.
   */
  thinking?: ('provider-default' | 'none' | 'low' | 'medium' | 'high' | 'xhigh') | null;
  /**
   * Add a key for each provider you use (OpenAI, DeepSeek, Gemini, Claude…). Then switch between their models from the console, or with the Provider and Model boxes above, without entering keys again.
   */
  providers?:
    | {
        provider:
          | 'anthropic'
          | 'openai'
          | 'google'
          | 'openrouter'
          | 'groq'
          | 'deepseek'
          | 'xai'
          | 'mistral'
          | 'together'
          | 'ollama'
          | 'custom';
        /**
         * A cheaper model from this provider for background work (sorting messages, helper tasks). Empty: the main model does everything.
         */
        fastModel?: string | null;
        /**
         * Stored encrypted and never shown again, not even to the agent. Empty: the provider's key from the environment, if set.
         */
        apiKey?: string | null;
        apiKeyHint?: string | null;
        /**
         * Only needed for your own server or a service not in the list, e.g. http://localhost:11434/v1 for Ollama.
         */
        baseURL?: string | null;
        id?: string | null;
      }[]
    | null;
  apiKey?: string | null;
  apiKeyHint?: string | null;
  baseURL?: string | null;
  fastModel?: string | null;
  voiceEnabled?: boolean | null;
  /**
   * A Gemini model that supports live audio. Choose from your account to see the ones your key can use.
   */
  voiceModel?: string | null;
  /**
   * Choose one to hear the difference in your next conversation.
   */
  voiceName?: string | null;
  /**
   * e.g. en-US, en-GB. Empty: it follows you.
   */
  voiceLanguage?: string | null;
  /**
   * Empty: the Google (Gemini) key from Model → Your providers, else GEMINI_API_KEY from the environment.
   */
  voiceApiKey?: string | null;
  voiceApiKeyHint?: string | null;
  /**
   * Empty: the newest everyday Gemini model on the key.
   */
  visionModel?: string | null;
  /**
   * Empty: the newest Gemini image model on the key.
   */
  imageModel?: string | null;
  mode?: ('ask' | 'drafts' | 'trusted' | 'full') | null;
  deletes?: ('never' | 'ask' | 'auto') | null;
  email?: ('never' | 'ask' | 'auto') | null;
  web?: boolean | null;
  /**
   * Read before every task. Its memory (Agent → Memory) adds what it learns over time.
   */
  persona?: string | null;
  /**
   * It sorts the message (lead, question, spam), writes a summary in the notes and marks obvious spam. It never replies on its own.
   */
  triage?: boolean | null;
  triageDraft?: boolean | null;
  /**
   * After each routine and each new message it reads: what it did, what it changed and anything waiting for your approval. Every one also appears under the bell in the Agent console.
   */
  notifyAuto?: boolean | null;
  /**
   * Empty: ADMIN_NOTIFY_EMAIL, else the address in Site settings. Needs email set up (RESEND_API_KEY).
   */
  notifyEmail?: string | null;
  maxSteps?: number | null;
  dailyRuns?: number | null;
  /**
   * Keeps the model bill predictable.
   */
  dailyTokens?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Where Keeper looks for businesses that need a website, what you offer them, and how messages are sent. Nothing is sent without you: every message waits for you in the phone app.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach".
 */
export interface Outreach {
  id: number;
  /**
   * Each morning Keeper finds new businesses in the areas below, checks their websites and writes messages for the best ones. You get a notification when they're ready.
   */
  enabled?: boolean | null;
  /**
   * A neighbourhood or town with its city (e.g. “Lekki Phase I, Lagos”, “Wuse, Abuja”, “Peckham, London”), not a whole county. Areas take turns, a few businesses at a time.
   */
  searches?:
    | {
        area: string;
        country: 'NG' | 'GH' | 'KE' | 'ZA' | 'GB' | 'IE' | 'US' | 'CA';
        on?: boolean | null;
        kinds: (
          | 'food'
          | 'beauty'
          | 'health'
          | 'education'
          | 'stay'
          | 'shops'
          | 'property'
          | 'professional'
          | 'fitness'
          | 'auto'
          | 'events'
          | 'trades'
        )[];
        id?: string | null;
      }[]
    | null;
  /**
   * Found and checked each morning.
   */
  dailyNew?: number | null;
  /**
   * Written for the best of them, for you to send.
   */
  dailyReady?: number | null;
  /**
   * In your words, with a starting price if you like. Keeper only promises what's written here.
   */
  offer?: string | null;
  /**
   * How messages are signed.
   */
  senderName?: string | null;
  /**
   * For the “Get this website” button on previews.
   */
  senderPhone?: string | null;
  /**
   * Put at the end of emails (required by law in the UK and US).
   */
  address?: string | null;
  /**
   * A free sample homepage for the most promising businesses, linked in the message.
   */
  previews?: boolean | null;
  previewScore?: number | null;
  followUp?: boolean | null;
  followUpDays?: number | null;
  gmail?: string | null;
  /**
   * Keep it low: a new Gmail sending many emails to strangers gets flagged.
   */
  dailyEmails?: number | null;
  /**
   * https://script.google.com/macros/s/…/exec
   */
  gmailScriptUrl?: string | null;
  /**
   * The password you set in the script. Stored encrypted.
   */
  gmailScriptSecret?: string | null;
  gmailScriptSecretHint?: string | null;
  /**
   * Only on hosts that allow email ports (not Render's free plan): myaccount.google.com/apppasswords, with 2-Step Verification on.
   */
  gmailPassword?: string | null;
  gmailPasswordHint?: string | null;
  /**
   * Free: 25,000 checks a day. Or set PAGESPEED_API_KEY in the environment.
   */
  pagespeedKey?: string | null;
  pagespeedKeyHint?: string | null;
  /**
   * Every Monday Keeper drafts a post on something business owners search for, so people find you on Google. It waits for you to publish it.
   */
  weeklyPost?: boolean | null;
  findRoutine?: (number | null) | AgentRoutine;
  postRoutine?: (number | null) | AgentRoutine;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        titleMuted?: T;
        titleMain?: T;
        lead?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        background?: T;
        card?:
          | T
          | {
              enabled?: T;
              title?: T;
              subtitle?: T;
              href?: T;
              image?: T;
              frame?: T;
            };
        note?: T;
        showStack?: T;
      };
  intro?:
    | T
    | {
        enabled?: T;
        statement?: T;
        sub?: T;
        projects?:
          | T
          | {
              value?: T;
              text?: T;
            };
        satisfaction?:
          | T
          | {
              value?: T;
              label?: T;
            };
        years?:
          | T
          | {
              value?: T;
              text?: T;
            };
        speed?:
          | T
          | {
              title?: T;
              text?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              brand?: T;
              by?: T;
            };
        showTicker?: T;
      };
  work?:
    | T
    | {
        enabled?: T;
        marquee?: T;
        projects?: T;
      };
  services?:
    | T
    | {
        enabled?: T;
        label?: T;
        intro?: T;
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        texture?: T;
        iso?: T;
      };
  mission?:
    | T
    | {
        enabled?: T;
        label?: T;
        statement?: T;
        body?: T;
        modelsIntro?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  tenets?:
    | T
    | {
        enabled?: T;
        marquee?: T;
        description?: T;
        cardFooter?: T;
        items?:
          | T
          | {
              title?: T;
              tag?: T;
              body?: T;
              id?: T;
            };
        showTicker?: T;
      };
  showcase?:
    | T
    | {
        enabled?: T;
        image?: T;
        lead?: T;
        pill?: T;
        title?: T;
      };
  process?:
    | T
    | {
        enabled?: T;
        label?: T;
        title?: T;
        texture?: T;
        iso?: T;
        steps?:
          | T
          | {
              title?: T;
              tag?: T;
              body?: T;
              id?: T;
            };
        closing?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  studio?:
    | T
    | {
        enabled?: T;
        statement?: T;
        intro?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        exploreLabel?: T;
        disciplines?:
          | T
          | {
              name?: T;
              role?: T;
              body?: T;
              image?: T;
              href?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        enabled?: T;
        marquee?: T;
        intro?: T;
        billing?:
          | T
          | {
              left?: T;
              right?: T;
              hint?: T;
              leftNote?: T;
              rightNote?: T;
            };
        cardImage?: T;
        tiers?:
          | T
          | {
              name?: T;
              price?: T;
              dark?: T;
              blurb?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
            };
        showTicker?: T;
      };
  faq?:
    | T
    | {
        enabled?: T;
        label?: T;
        sub?: T;
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  journal?:
    | T
    | {
        enabled?: T;
        marquee?: T;
        intro?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        count?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        lead?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  mosaic?:
    | T
    | {
        image?: T;
        id?: T;
      };
  story?:
    | T
    | {
        enabled?: T;
        label?: T;
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        showStats?: T;
      };
  crafts?:
    | T
    | {
        enabled?: T;
        label?: T;
        statement?: T;
        lead?: T;
        showStack?: T;
        cards?:
          | T
          | {
              title?: T;
              body?: T;
              shape?: T;
              id?: T;
            };
      };
  showTenets?: T;
  showFaq?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  showAccordion?: T;
  showProcess?: T;
  list?:
    | T
    | {
        enabled?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  showFaq?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  image?: T;
  marquee?: T;
  note?: T;
  productsLabel?: T;
  clientsLabel?: T;
  caseStudy?:
    | T
    | {
        productKicker?: T;
        caseKicker?: T;
        nextProduct?: T;
        nextCase?: T;
        ctaTitle?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  showFaq?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page_select".
 */
export interface JournalPageSelect<T extends boolean = true> {
  marquee?: T;
  intro?: T;
  post?:
    | T
    | {
        authorLabel?: T;
        dateLabel?: T;
        byLabel?: T;
        moreTitle?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  split?:
    | T
    | {
        title?: T;
        lead?: T;
        image?: T;
        visualTitle?: T;
        form?:
          | T
          | {
              nameLabel?: T;
              namePlaceholder?: T;
              emailLabel?: T;
              emailPlaceholder?: T;
              budgetLabel?: T;
              budgets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              messageLabel?: T;
              messagePlaceholder?: T;
              submitLabel?: T;
              successMessage?: T;
              errorMessage?: T;
            };
      };
  call?:
    | T
    | {
        enabled?: T;
        image?: T;
        label?: T;
        title?: T;
        body?: T;
        showSocials?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  showFaq?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        showHire?: T;
        hire?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  footer?:
    | T
    | {
        background?: T;
        blurb?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        followLabel?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        copyright?: T;
        showWordmark?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  url?: T;
  founder?:
    | T
    | {
        name?: T;
        alias?: T;
        role?: T;
        photo?: T;
        monogram?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  avatars?: T;
  stack?:
    | T
    | {
        text?: T;
        id?: T;
      };
  email?: T;
  location?: T;
  phone?: T;
  phoneHref?: T;
  socials?:
    | T
    | {
        label?: T;
        icon?: T;
        href?: T;
        id?: T;
      };
  ticker?:
    | T
    | {
        enabled?: T;
        tag?: T;
        message?: T;
      };
  title?: T;
  titleTemplate?: T;
  description?: T;
  ogImage?: T;
  notifications?:
    | T
    | {
        to?: T;
        autoReply?: T;
        autoReplySubject?: T;
        autoReplyBody?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "effects_select".
 */
export interface EffectsSelect<T extends boolean = true> {
  cursorLens?: T;
  lensSize?: T;
  navGlass?: T;
  footerGlass?: T;
  heroDew?: T;
  pageTransitions?: T;
  smoothScroll?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found_select".
 */
export interface NotFoundSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        intro?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  contactNote?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        intro?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  contactNote?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent_select".
 */
export interface AgentSelect<T extends boolean = true> {
  enabled?: T;
  name?: T;
  provider?: T;
  model?: T;
  thinking?: T;
  providers?:
    | T
    | {
        provider?: T;
        fastModel?: T;
        apiKey?: T;
        apiKeyHint?: T;
        baseURL?: T;
        id?: T;
      };
  apiKey?: T;
  apiKeyHint?: T;
  baseURL?: T;
  fastModel?: T;
  voiceEnabled?: T;
  voiceModel?: T;
  voiceName?: T;
  voiceLanguage?: T;
  voiceApiKey?: T;
  voiceApiKeyHint?: T;
  visionModel?: T;
  imageModel?: T;
  mode?: T;
  deletes?: T;
  email?: T;
  web?: T;
  persona?: T;
  triage?: T;
  triageDraft?: T;
  notifyAuto?: T;
  notifyEmail?: T;
  maxSteps?: T;
  dailyRuns?: T;
  dailyTokens?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach_select".
 */
export interface OutreachSelect<T extends boolean = true> {
  enabled?: T;
  searches?:
    | T
    | {
        area?: T;
        country?: T;
        on?: T;
        kinds?: T;
        id?: T;
      };
  dailyNew?: T;
  dailyReady?: T;
  offer?: T;
  senderName?: T;
  senderPhone?: T;
  address?: T;
  previews?: T;
  previewScore?: T;
  followUp?: T;
  followUpDays?: T;
  gmail?: T;
  dailyEmails?: T;
  gmailScriptUrl?: T;
  gmailScriptSecret?: T;
  gmailScriptSecretHint?: T;
  gmailPassword?: T;
  gmailPasswordHint?: T;
  pagespeedKey?: T;
  pagespeedKeyHint?: T;
  weeklyPost?: T;
  findRoutine?: T;
  postRoutine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}